server:
  port: 18000
knife4j:
  enableAggregation: true
  cloud:
    enable: true
    routes:
      - name: 授权模块
        uri: 127.0.0.1/blade-auth
        location: /v2/api-docs
      - name: 工作台模块
        uri: 127.0.0.1/blade-desk
        location: /v2/api-docs
      - name: 系统模块
        uri: 127.0.0.1/blade-system
        location: /v2/api-docs
